# jekyll-theme-h2o-ac
version: 1.1.14

# Site settings é…ç½®ç«™ç‚¹
title: 'Can1425çš„åšå®¢'
description: 'ä¸ªäººçš„ä¸€ä¸ªæŠ€æœ¯åšå®¢ç«™ç‚¹ï¼Œä¸»è¦ç”¨äºè®°å½•ä¸ªäººåœ¨å­¦ä¹ è¿‡ç¨‹ä¸­é‡åˆ°çš„æŠ€æœ¯é—®é¢˜åŠè§£å†³æ–¹æ³•ã€æŠ€æœ¯å®éªŒï¼Œä»¥åŠä¸€äº›æ¯”è¾ƒæœ‰è¶£çš„äº‹æƒ…ã€‚'
keyword: 'Can1425ï¼ŒCan1425çš„åšå®¢ï¼ŒmPython'
url: '' # your host

# when build blog on server, if you don't need baseurl, you should leave this value blank.
# åœ¨æœåŠ¡å™¨ä¸Šå»ºç«™æ—¶ï¼Œå¦‚æœä½ ä¸éœ€è¦å­åŸŸåï¼Œè¯·å°†è¿™ä¸€æ ¼ç•™ç©º
# if you're using GitHub Pages, set baseurl to your blog's .
# å¦‚æœä½ åœ¨ä½¿ç”¨ GitHub Pages, è¯·å°† baseurl è®¾ç½®ä¸ºä½ çš„ç½‘å€çš„å­åŸŸå
# for example, if your site is "kaeyleo.github.io", then this url should leave blank.
# ä¾‹å¦‚ï¼Œå½“ä½ çš„åŸŸåæ˜¯ "kaeyleo.github.io"  æ—¶ï¼Œè¿™ä¸ª url éœ€è¦ç•™ç©º
# but if your created a repo named "myblog", and the site is "kaeyleo.github.io/myblog", change baseurl to '/myblog'
# ä½†æ˜¯ï¼Œå¦‚æœä½ åˆ›å»ºäº†ä¸€ä¸ªå« "myblog" çš„ç½‘ç«™ï¼Œæ­¤æ—¶ç½‘å€ä¼šå˜æˆ "kaeyleo.github.io/myblog" ï¼Œè¿™æ—¶å†å°† baseurl è®¾ç½®ä¸º '/myblog'
baseurl: ''

# Github
github:
  enabled: true
  owner: zhonger
  repository: jekyll-theme-H2O-ac

# PWA
pwa:
  color: '#81BBFF'
  short_name: 'lisz'

# International
language: zh-cn

# Navigation links
nav:
  ğŸ é¦–é¡µ: '/'
  ğŸ·ï¸æ ‡ç­¾: '/tags.html'
  ğŸ“†å½’æ¡£: '/archives.html'
  ğŸ”—å‹é“¾: '/links.html'
  about:   
    RSS: '/feed.xml'

# Gray for the whole site å…¨ç«™ç°è‰²
gray: false

# Formats
# æ—¶é—´æ ¼å¼ï¼ˆTime formatï¼‰ï¼š0 -- 2022-04-29    1 -- 29 Apr 2022   2 -- 2022å¹´4æœˆ29æ—¥
formats:
  time: 0   

# Favicon
favicon: "/assets/icons/default.svg"

# Footer
footer:
  since: 2022

# Author é…ç½®åšä¸»ä¿¡æ¯
author: 'Can1425'
nickname: 'Can1425'
bio: 'å…¨æ ˆå¼€å‘è€…ï¼Œçƒ­çˆ±å‰ç«¯ã€è¿ç»´å’Œæ¶æ„è®¾è®¡'
avatar: '/assets/icons/default.svg'

# Search
search: true

# Night mode
nightMode: false

# Comments è¯„è®ºåŠŸèƒ½
comments:
  disqus: false
  disqus_url: 'https://h2o-ac.disqus.com/embed.js'
  waline: false
  waline_url: 'https://can1425-waline.wxxh.xyz/'
  waline_reaction: false
  waline_locale: 

# MathJax å…¬å¼æ”¯æŒ by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color ä¸»é¢˜çš®è‚¤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings é…ç½®ç¤¾äº¤ç½‘ç«™
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  # google-scholar: 'https://scholar.google.com/citations?user=AUupIooAAAAJ'
  # researchgate: 'https://www.researchgate.net/profile/Shengzhou-Li'
  # ORCID: 'https://orcid.org/0000-0001-6973-3825'
  # github: 'https://github.com/zhonger'
  # linkedin: 'https://www.linkedin.com/in/shengzhouli/'
  # segmentfault: 'https://segmentfault.com/u/wuwozhonger'

# Links å‹æƒ…é“¾æ¥
links:
   'ouyhq2011çš„åšå®¢': 'https://ouyanghongqian.top'
  # 'Mr Li': 'https://lisz.me'

# Supports èµåŠ©å•†
supports:
  upyun: 
  webify: 

# Beian å¤‡æ¡ˆå·
#beian: 'æ²ªICPå¤‡xxxxxxxxå·'

# CC License
cclicense: true

# CNZZ Analytics
# cnzz: 1234567891
cnzz: 

# Busuanzi Analytics
busuanzi: true

# Umami Analytics
umami:
  status: 
  id: 
  js: 

# Google Analytics
# google_analytics: UA-XXXXXXXXX-X
google_analytics: 

# Google Search
google_search: 

# ToS
tos: /tos.html

# Tags è®¾ç½®æ ‡ç­¾
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
pagination:
  enabled: true
  per_page: 5
  permalink: 'page:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md', '*.gemspec', '*.gem']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Prism settings
# Support all offical and extended themes
# Please visit https://prismjs.com and https://github.com/PrismJS/prism-themes/tree/master/themes to check the supported theme names
prism:
  theme: one-light
  line_numbers: true

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:categories/:title.html

# Extlinks
extlinks:
  attributes: {rel: nofollow, target: _blank, class: extlinks}
  # rel_exclude: ['host1.com', 'host2.net']
  # class_exclude: ['host1.com', 'host2.net']

# Mermaid
mermaid: true

# Webpusher
webpusher: false

# Foreverblog
foreverblog: false

# Wormhole
wormhole: false

# Alive time
alivetime: false
alivestart: "12/23/2021"

# TOC
toc: true
# <div class="title">{% if title %} {{title}} {% else %} {{default_title}} {% endif %}</div>
# premonition
premonition:
  default:
    template: '<div class="premonition {{type}}">
          <div class="header">
            <svg class="icon {{type}}" aria-hidden="true">
                <use xlink:href="#icon-{{type}}"></use>
            </svg>
            <div class="title"> {{title}} </div>
          </div>
          <div class="content">
            {{content}}
          </div>
        </div>'
  types:
    citation:
      template: '<div class="premonition {{type}}">
          <div class="header">
            <svg class="icon {{type}}" aria-hidden="true">
                <use xlink:href="#icon-{{type}}"></use>
            </svg>     
          </div>
          <div class="content">
            {{content}}
          </div>
          {% if title %}<div class="ref"> ------ {{title}} </div>{% endif %}
        </div>'
      default_title: ''
    note:
      default_title: 'Note'
    info:
      default_title: 'Info'
    warning:
      default_title: 'Warning'
    error:
      default_title: 'Error'

# Plugins
plugins: [jekyll-paginate-v2, jekyll-feed, jekyll-sitemap, premonition, h2o-ac-jekyll-extlinks]
